<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SurrealDb.Embedded.RocksDb" />
    <PackageReference Include="SurrealDb.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Azure.Cosmos.LightEmulator.Core.csproj" />
  </ItemGroup>

</Project>
