<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Azure.Cosmos" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Azure.Cosmos.LightEmulator.Core.csproj" />
    <ProjectReference Include="..\..\src\Host\Azure.Cosmos.LightEmulator.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <Import Project="build\CloneSdkTests.targets" Condition="Exists('build\CloneSdkTests.targets')" />

</Project>